// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: message/v1/message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息体
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 发送方：0=用户 1=AI
	Sender int32 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// 消息类型：0=聊天 1=小纸条
	MessageType int32 `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 小纸条是否锁定
	IsLocked bool `protobuf:"varint,4,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	// 小纸条解锁所需金币
	UnlockCoins int32 `protobuf:"varint,5,opt,name=unlock_coins,json=unlockCoins,proto3" json:"unlock_coins,omitempty"`
	// 文本内容（锁定时可为空或返回占位）
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 创建时间 YYYY-MM-DD HH:MM:SS
	CreatedAt     string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSender() int32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *Message) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *Message) GetUnlockCoins() int32 {
	if x != nil {
		return x.UnlockCoins
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 消息列表请求
type GetMessageListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码，从1开始（默认1）
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页条数（默认20，最大100）
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 仅小纸条（true=只返回 message_type=1）
	OnlyNotes     bool `protobuf:"varint,3,opt,name=only_notes,json=onlyNotes,proto3" json:"only_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListRequest) Reset() {
	*x = GetMessageListRequest{}
	mi := &file_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListRequest) ProtoMessage() {}

func (x *GetMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetMessageListRequest) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessageListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMessageListRequest) GetOnlyNotes() bool {
	if x != nil {
		return x.OnlyNotes
	}
	return false
}

// 消息列表响应
type GetMessageListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总条数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前页消息列表
	List          []*Message `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListReply) Reset() {
	*x = GetMessageListReply{}
	mi := &file_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListReply) ProtoMessage() {}

func (x *GetMessageListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListReply.ProtoReflect.Descriptor instead.
func (*GetMessageListReply) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMessageListReply) GetList() []*Message {
	if x != nil {
		return x.List
	}
	return nil
}

// 解锁小纸条请求
type UnlockMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标消息ID
	MessageId     int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockMessageRequest) Reset() {
	*x = UnlockMessageRequest{}
	mi := &file_message_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockMessageRequest) ProtoMessage() {}

func (x *UnlockMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockMessageRequest.ProtoReflect.Descriptor instead.
func (*UnlockMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 解锁小纸条响应
type UnlockMessageReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功（金币足够且状态有效）
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 解锁后剩余金币（未开启金币体系时可为0）
	RemainingCoins int32 `protobuf:"varint,2,opt,name=remaining_coins,json=remainingCoins,proto3" json:"remaining_coins,omitempty"`
	// 解锁后的完整消息
	Message       *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockMessageReply) Reset() {
	*x = UnlockMessageReply{}
	mi := &file_message_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockMessageReply) ProtoMessage() {}

func (x *UnlockMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockMessageReply.ProtoReflect.Descriptor instead.
func (*UnlockMessageReply) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockMessageReply) GetRemainingCoins() int32 {
	if x != nil {
		return x.RemainingCoins
	}
	return 0
}

func (x *UnlockMessageReply) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_message_v1_message_proto protoreflect.FileDescriptor

const file_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x18message/v1/message.proto\x12\x0eapi.message.v1\x1a\x1cgoogle/api/annotations.proto\"\xcd\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\x05R\x06sender\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\x12\x1b\n" +
	"\tis_locked\x18\x04 \x01(\bR\bisLocked\x12!\n" +
	"\funlock_coins\x18\x05 \x01(\x05R\vunlockCoins\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"g\n" +
	"\x15GetMessageListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"only_notes\x18\x03 \x01(\bR\tonlyNotes\"X\n" +
	"\x13GetMessageListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12+\n" +
	"\x04list\x18\x02 \x03(\v2\x17.api.message.v1.MessageR\x04list\"5\n" +
	"\x14UnlockMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\x8a\x01\n" +
	"\x12UnlockMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fremaining_coins\x18\x02 \x01(\x05R\x0eremainingCoins\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x17.api.message.v1.MessageR\amessage2\x90\x02\n" +
	"\x0eMessageService\x12v\n" +
	"\x0eGetMessageList\x12%.api.message.v1.GetMessageListRequest\x1a#.api.message.v1.GetMessageListReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/message/list\x12\x85\x01\n" +
	"\rUnlockMessage\x12$.api.message.v1.UnlockMessageRequest\x1a\".api.message.v1.UnlockMessageReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/message/{message_id}/unlockB\x1dZ\x1bpet-angel/api/message/v1;v1b\x06proto3"

var (
	file_message_v1_message_proto_rawDescOnce sync.Once
	file_message_v1_message_proto_rawDescData []byte
)

func file_message_v1_message_proto_rawDescGZIP() []byte {
	file_message_v1_message_proto_rawDescOnce.Do(func() {
		file_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_v1_message_proto_rawDesc), len(file_message_v1_message_proto_rawDesc)))
	})
	return file_message_v1_message_proto_rawDescData
}

var file_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_v1_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: api.message.v1.Message
	(*GetMessageListRequest)(nil), // 1: api.message.v1.GetMessageListRequest
	(*GetMessageListReply)(nil),   // 2: api.message.v1.GetMessageListReply
	(*UnlockMessageRequest)(nil),  // 3: api.message.v1.UnlockMessageRequest
	(*UnlockMessageReply)(nil),    // 4: api.message.v1.UnlockMessageReply
}
var file_message_v1_message_proto_depIdxs = []int32{
	0, // 0: api.message.v1.GetMessageListReply.list:type_name -> api.message.v1.Message
	0, // 1: api.message.v1.UnlockMessageReply.message:type_name -> api.message.v1.Message
	1, // 2: api.message.v1.MessageService.GetMessageList:input_type -> api.message.v1.GetMessageListRequest
	3, // 3: api.message.v1.MessageService.UnlockMessage:input_type -> api.message.v1.UnlockMessageRequest
	2, // 4: api.message.v1.MessageService.GetMessageList:output_type -> api.message.v1.GetMessageListReply
	4, // 5: api.message.v1.MessageService.UnlockMessage:output_type -> api.message.v1.UnlockMessageReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_v1_message_proto_init() }
func file_message_v1_message_proto_init() {
	if File_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_v1_message_proto_rawDesc), len(file_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_v1_message_proto_goTypes,
		DependencyIndexes: file_message_v1_message_proto_depIdxs,
		MessageInfos:      file_message_v1_message_proto_msgTypes,
	}.Build()
	File_message_v1_message_proto = out.File
	file_message_v1_message_proto_goTypes = nil
	file_message_v1_message_proto_depIdxs = nil
}
