// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 关注请求
type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type FollowUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserReply) Reset() {
	*x = FollowUserReply{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserReply) ProtoMessage() {}

func (x *FollowUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserReply.ProtoReflect.Descriptor instead.
func (*FollowUserReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 取消关注请求
type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type UnfollowUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserReply) Reset() {
	*x = UnfollowUserReply{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserReply) ProtoMessage() {}

func (x *UnfollowUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserReply.ProtoReflect.Descriptor instead.
func (*UnfollowUserReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 帖子简要信息（用于主页/点赞列表）
type PostBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 帖子ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                              // 标题
	PostType      int32                  `protobuf:"varint,3,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`       // 0图文 1视频
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`        // 封面URL
	LikedCount    int32                  `protobuf:"varint,5,opt,name=liked_count,json=likedCount,proto3" json:"liked_count,omitempty"` // 点赞数
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`     // 创建时间 YYYY-MM-DD HH:MM:SS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBrief) Reset() {
	*x = PostBrief{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBrief) ProtoMessage() {}

func (x *PostBrief) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBrief.ProtoReflect.Descriptor instead.
func (*PostBrief) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *PostBrief) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostBrief) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostBrief) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *PostBrief) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PostBrief) GetLikedCount() int32 {
	if x != nil {
		return x.LikedCount
	}
	return 0
}

func (x *PostBrief) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 用户主页请求
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 用户主页响应
type GetUserProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`                             // 头像URL
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                         // 昵称
	PetName       string                 `protobuf:"bytes,3,opt,name=pet_name,json=petName,proto3" json:"pet_name,omitempty"`            // 宠物名称
	PetSex        int32                  `protobuf:"varint,4,opt,name=pet_sex,json=petSex,proto3" json:"pet_sex,omitempty"`              // 宠物性别 0未知/1男/2女
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`                                 // 宠物品类
	Weight        int32                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`                            // 体重(kg)
	Hobby         string                 `protobuf:"bytes,7,opt,name=hobby,proto3" json:"hobby,omitempty"`                               // 爱好
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                   // 简介
	Posts         []*PostBrief           `protobuf:"bytes,9,rep,name=posts,proto3" json:"posts,omitempty"`                               // 最近的帖子
	IsFollowed    bool                   `protobuf:"varint,10,opt,name=is_followed,json=isFollowed,proto3" json:"is_followed,omitempty"` // 当前登录用户是否已关注该用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReply) Reset() {
	*x = GetUserProfileReply{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReply) ProtoMessage() {}

func (x *GetUserProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReply.ProtoReflect.Descriptor instead.
func (*GetUserProfileReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserProfileReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserProfileReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserProfileReply) GetPetName() string {
	if x != nil {
		return x.PetName
	}
	return ""
}

func (x *GetUserProfileReply) GetPetSex() int32 {
	if x != nil {
		return x.PetSex
	}
	return 0
}

func (x *GetUserProfileReply) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetUserProfileReply) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GetUserProfileReply) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *GetUserProfileReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetUserProfileReply) GetPosts() []*PostBrief {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetUserProfileReply) GetIsFollowed() bool {
	if x != nil {
		return x.IsFollowed
	}
	return false
}

// 用户简要
type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserBrief) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 关注列表请求/响应
type GetFollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowListRequest) Reset() {
	*x = GetFollowListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListRequest) ProtoMessage() {}

func (x *GetFollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListRequest.ProtoReflect.Descriptor instead.
func (*GetFollowListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFollowListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserBrief           `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowListReply) Reset() {
	*x = GetFollowListReply{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListReply) ProtoMessage() {}

func (x *GetFollowListReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListReply.ProtoReflect.Descriptor instead.
func (*GetFollowListReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFollowListReply) GetList() []*UserBrief {
	if x != nil {
		return x.List
	}
	return nil
}

// 点赞列表请求/响应
type GetLikeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeListRequest) Reset() {
	*x = GetLikeListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeListRequest) ProtoMessage() {}

func (x *GetLikeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeListRequest.ProtoReflect.Descriptor instead.
func (*GetLikeListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetLikeListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikeListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLikeListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetLikeListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*PostBrief           `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeListReply) Reset() {
	*x = GetLikeListReply{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeListReply) ProtoMessage() {}

func (x *GetLikeListReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeListReply.ProtoReflect.Descriptor instead.
func (*GetLikeListReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetLikeListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLikeListReply) GetList() []*PostBrief {
	if x != nil {
		return x.List
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"9\n" +
	"\x11FollowUserRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\"+\n" +
	"\x0fFollowUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x13UnfollowUserRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\"-\n" +
	"\x11UnfollowUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xab\x01\n" +
	"\tPostBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tpost_type\x18\x03 \x01(\x05R\bpostType\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vliked_count\x18\x05 \x01(\x05R\n" +
	"likedCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb0\x02\n" +
	"\x13GetUserProfileReply\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x19\n" +
	"\bpet_name\x18\x03 \x01(\tR\apetName\x12\x17\n" +
	"\apet_sex\x18\x04 \x01(\x05R\x06petSex\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05hobby\x18\a \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12,\n" +
	"\x05posts\x18\t \x03(\v2\x16.api.user.v1.PostBriefR\x05posts\x12\x1f\n" +
	"\vis_followed\x18\n" +
	" \x01(\bR\n" +
	"isFollowed\"O\n" +
	"\tUserBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"`\n" +
	"\x14GetFollowListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x12GetFollowListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.api.user.v1.UserBriefR\x04list\"^\n" +
	"\x12GetLikeListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"T\n" +
	"\x10GetLikeListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.api.user.v1.PostBriefR\x04list2\xcb\x04\n" +
	"\vUserService\x12f\n" +
	"\n" +
	"FollowUser\x12\x1e.api.user.v1.FollowUserRequest\x1a\x1c.api.user.v1.FollowUserReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/follow\x12n\n" +
	"\fUnfollowUser\x12 .api.user.v1.UnfollowUserRequest\x1a\x1e.api.user.v1.UnfollowUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/user/unfollow\x12z\n" +
	"\x0eGetUserProfile\x12\".api.user.v1.GetUserProfileRequest\x1a .api.user.v1.GetUserProfileReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/{user_id}/profile\x12w\n" +
	"\rGetFollowList\x12!.api.user.v1.GetFollowListRequest\x1a\x1f.api.user.v1.GetFollowListReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/{user_id}/follows\x12o\n" +
	"\vGetLikeList\x12\x1f.api.user.v1.GetLikeListRequest\x1a\x1d.api.user.v1.GetLikeListReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/user/{user_id}/likesB\x1aZ\x18pet-angel/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_v1_user_proto_goTypes = []any{
	(*FollowUserRequest)(nil),     // 0: api.user.v1.FollowUserRequest
	(*FollowUserReply)(nil),       // 1: api.user.v1.FollowUserReply
	(*UnfollowUserRequest)(nil),   // 2: api.user.v1.UnfollowUserRequest
	(*UnfollowUserReply)(nil),     // 3: api.user.v1.UnfollowUserReply
	(*PostBrief)(nil),             // 4: api.user.v1.PostBrief
	(*GetUserProfileRequest)(nil), // 5: api.user.v1.GetUserProfileRequest
	(*GetUserProfileReply)(nil),   // 6: api.user.v1.GetUserProfileReply
	(*UserBrief)(nil),             // 7: api.user.v1.UserBrief
	(*GetFollowListRequest)(nil),  // 8: api.user.v1.GetFollowListRequest
	(*GetFollowListReply)(nil),    // 9: api.user.v1.GetFollowListReply
	(*GetLikeListRequest)(nil),    // 10: api.user.v1.GetLikeListRequest
	(*GetLikeListReply)(nil),      // 11: api.user.v1.GetLikeListReply
}
var file_user_v1_user_proto_depIdxs = []int32{
	4,  // 0: api.user.v1.GetUserProfileReply.posts:type_name -> api.user.v1.PostBrief
	7,  // 1: api.user.v1.GetFollowListReply.list:type_name -> api.user.v1.UserBrief
	4,  // 2: api.user.v1.GetLikeListReply.list:type_name -> api.user.v1.PostBrief
	0,  // 3: api.user.v1.UserService.FollowUser:input_type -> api.user.v1.FollowUserRequest
	2,  // 4: api.user.v1.UserService.UnfollowUser:input_type -> api.user.v1.UnfollowUserRequest
	5,  // 5: api.user.v1.UserService.GetUserProfile:input_type -> api.user.v1.GetUserProfileRequest
	8,  // 6: api.user.v1.UserService.GetFollowList:input_type -> api.user.v1.GetFollowListRequest
	10, // 7: api.user.v1.UserService.GetLikeList:input_type -> api.user.v1.GetLikeListRequest
	1,  // 8: api.user.v1.UserService.FollowUser:output_type -> api.user.v1.FollowUserReply
	3,  // 9: api.user.v1.UserService.UnfollowUser:output_type -> api.user.v1.UnfollowUserReply
	6,  // 10: api.user.v1.UserService.GetUserProfile:output_type -> api.user.v1.GetUserProfileReply
	9,  // 11: api.user.v1.UserService.GetFollowList:output_type -> api.user.v1.GetFollowListReply
	11, // 12: api.user.v1.UserService.GetLikeList:output_type -> api.user.v1.GetLikeListReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
