// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: community/v1/community.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帖子分类
type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分类名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_community_v1_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_community_v1_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{1}
}

type GetCategoriesReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类列表
	Categories    []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesReply) Reset() {
	*x = GetCategoriesReply{}
	mi := &file_community_v1_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesReply) ProtoMessage() {}

func (x *GetCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesReply.ProtoReflect.Descriptor instead.
func (*GetCategoriesReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoriesReply) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// 用户简要信息（用于帖子/评论作者）
type UserBrief struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像URL
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 当前登录用户是否已关注该作者
	IsFollowed    bool `protobuf:"varint,4,opt,name=is_followed,json=isFollowed,proto3" json:"is_followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_community_v1_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{3}
}

func (x *UserBrief) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBrief) GetIsFollowed() bool {
	if x != nil {
		return x.IsFollowed
	}
	return false
}

// 帖子实体
type Post struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 作者信息
	User *UserBrief `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// 分类ID
	CategoryId int64 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 标题
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// 文本内容
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// 帖子类型：0=图文 1=视频（与发布时保持一致）
	PostType int32 `protobuf:"varint,6,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	// 图片URL列表（图文）
	ImageUrls []string `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	// 视频URL（视频）
	VideoUrl string `protobuf:"bytes,8,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	// 封面URL（可选，用于列表首帧展示）
	CoverUrl string `protobuf:"bytes,9,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	// 位置文本（可选，例如城市/商圈）
	Locate string `protobuf:"bytes,10,opt,name=locate,proto3" json:"locate,omitempty"`
	// 标签（可选，最多若干个，按业务约束）
	Tags []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// 点赞数
	LikedCount int32 `protobuf:"varint,12,opt,name=liked_count,json=likedCount,proto3" json:"liked_count,omitempty"`
	// 评论数
	CommentCount int32 `protobuf:"varint,13,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	// 创建时间 YYYY-MM-DD HH:MM:SS
	CreatedAt string `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 当前用户是否已点赞
	IsLiked bool `protobuf:"varint,15,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	// 是否私密（私密仅自己可见）
	IsPrivate     bool `protobuf:"varint,16,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_community_v1_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{4}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetUser() *UserBrief {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Post) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *Post) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Post) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Post) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Post) GetLocate() string {
	if x != nil {
		return x.Locate
	}
	return ""
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetLikedCount() int32 {
	if x != nil {
		return x.LikedCount
	}
	return 0
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Post) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Post) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

// 帖子列表查询参数
type GetPostListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类过滤（可空，为0或缺省则为全部分类）
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 帖子类型过滤：-1=全部 0=图文 1=视频（默认-1）
	PostType int32 `protobuf:"varint,2,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	// 排序字段：created=按创建时间倒序、liked=按点赞数倒序（默认created）
	Sort string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 页码，从1开始（默认1）
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	// 每页条数（默认20，最大100；超出按100处理）
	PageSize      int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListRequest) Reset() {
	*x = GetPostListRequest{}
	mi := &file_community_v1_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListRequest) ProtoMessage() {}

func (x *GetPostListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListRequest.ProtoReflect.Descriptor instead.
func (*GetPostListRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostListRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GetPostListRequest) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *GetPostListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetPostListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPostListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 结果总条数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前页帖子列表
	List          []*Post `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListReply) Reset() {
	*x = GetPostListReply{}
	mi := &file_community_v1_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListReply) ProtoMessage() {}

func (x *GetPostListReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListReply.ProtoReflect.Descriptor instead.
func (*GetPostListReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPostListReply) GetList() []*Post {
	if x != nil {
		return x.List
	}
	return nil
}

// 帖子详情
type GetPostDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子ID
	PostId        int64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailRequest) Reset() {
	*x = GetPostDetailRequest{}
	mi := &file_community_v1_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailRequest) ProtoMessage() {}

func (x *GetPostDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailRequest.ProtoReflect.Descriptor instead.
func (*GetPostDetailRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostDetailRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostDetailReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子详情
	Post          *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailReply) Reset() {
	*x = GetPostDetailReply{}
	mi := &file_community_v1_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailReply) ProtoMessage() {}

func (x *GetPostDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailReply.ProtoReflect.Descriptor instead.
func (*GetPostDetailReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostDetailReply) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// 发帖
type CreatePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类ID（可空，为0或缺省则不归类）
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 标题（可选，建议<=50字）
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 文本内容（当 post_type=0 时必填，建议<=1000字）
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 帖子类型：0=图文 1=视频（默认0）
	PostType int32 `protobuf:"varint,4,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	// 图文贴：图片URL列表（最多9张，至少1张）
	ImageUrls []string `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	// 视频贴：视频URL（post_type=1 时必填）
	VideoUrl string `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	// 封面URL（可选，用于列表展示）
	CoverUrl string `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	// 位置（可选）
	Locate string `protobuf:"bytes,8,opt,name=locate,proto3" json:"locate,omitempty"`
	// 标签（可选）
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// 是否私密（默认false）
	IsPrivate     bool `protobuf:"varint,10,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_community_v1_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePostRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *CreatePostRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreatePostRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreatePostRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreatePostRequest) GetLocate() string {
	if x != nil {
		return x.Locate
	}
	return ""
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePostRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type CreatePostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新帖ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReply) Reset() {
	*x = CreatePostReply{}
	mi := &file_community_v1_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReply) ProtoMessage() {}

func (x *CreatePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReply.ProtoReflect.Descriptor instead.
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePostReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 帖子点赞
type LikePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子ID
	PostId        int64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_community_v1_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{11}
}

func (x *LikePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikePostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostReply) Reset() {
	*x = LikePostReply{}
	mi := &file_community_v1_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostReply) ProtoMessage() {}

func (x *LikePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostReply.ProtoReflect.Descriptor instead.
func (*LikePostReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{12}
}

func (x *LikePostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子ID
	PostId        int64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_community_v1_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{13}
}

func (x *UnlikePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UnlikePostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostReply) Reset() {
	*x = UnlikePostReply{}
	mi := &file_community_v1_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostReply) ProtoMessage() {}

func (x *UnlikePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostReply.ProtoReflect.Descriptor instead.
func (*UnlikePostReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{14}
}

func (x *UnlikePostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 评论
type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 评论者
	User *UserBrief `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// 内容（建议<=500字）
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 点赞数
	LikedCount int32 `protobuf:"varint,4,opt,name=liked_count,json=likedCount,proto3" json:"liked_count,omitempty"`
	// 创建时间 YYYY-MM-DD HH:MM:SS
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 当前用户是否点赞
	IsLiked       bool `protobuf:"varint,6,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_community_v1_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{15}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUser() *UserBrief {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLikedCount() int32 {
	if x != nil {
		return x.LikedCount
	}
	return 0
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetCommentListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 帖子ID
	PostId int64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// 页码，从1开始（默认1）
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页条数（默认20，最大100）
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListRequest) Reset() {
	*x = GetCommentListRequest{}
	mi := &file_community_v1_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListRequest) ProtoMessage() {}

func (x *GetCommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListRequest.ProtoReflect.Descriptor instead.
func (*GetCommentListRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{16}
}

func (x *GetCommentListRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetCommentListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCommentListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 结果总条数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前页评论列表
	List          []*Comment `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListReply) Reset() {
	*x = GetCommentListReply{}
	mi := &file_community_v1_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListReply) ProtoMessage() {}

func (x *GetCommentListReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListReply.ProtoReflect.Descriptor instead.
func (*GetCommentListReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{17}
}

func (x *GetCommentListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCommentListReply) GetList() []*Comment {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // 帖子ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`              // 评论内容（必填，建议<=500字）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_community_v1_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新评论ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply) Reset() {
	*x = CreateCommentReply{}
	mi := &file_community_v1_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply) ProtoMessage() {}

func (x *CreateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply.ProtoReflect.Descriptor instead.
func (*CreateCommentReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCommentReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论ID
	CommentId     int64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_community_v1_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{20}
}

func (x *LikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type LikeCommentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReply) Reset() {
	*x = LikeCommentReply{}
	mi := &file_community_v1_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReply) ProtoMessage() {}

func (x *LikeCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReply.ProtoReflect.Descriptor instead.
func (*LikeCommentReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{21}
}

func (x *LikeCommentReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikeCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论ID
	CommentId     int64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentRequest) Reset() {
	*x = UnlikeCommentRequest{}
	mi := &file_community_v1_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentRequest) ProtoMessage() {}

func (x *UnlikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentRequest.ProtoReflect.Descriptor instead.
func (*UnlikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{22}
}

func (x *UnlikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type UnlikeCommentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentReply) Reset() {
	*x = UnlikeCommentReply{}
	mi := &file_community_v1_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentReply) ProtoMessage() {}

func (x *UnlikeCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentReply.ProtoReflect.Descriptor instead.
func (*UnlikeCommentReply) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{23}
}

func (x *UnlikeCommentReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_community_v1_community_proto protoreflect.FileDescriptor

const file_community_v1_community_proto_rawDesc = "" +
	"\n" +
	"\x1ccommunity/v1/community.proto\x12\x10api.community.v1\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x16\n" +
	"\x14GetCategoriesRequest\"P\n" +
	"\x12GetCategoriesReply\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.api.community.v1.CategoryR\n" +
	"categories\"p\n" +
	"\tUserBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vis_followed\x18\x04 \x01(\bR\n" +
	"isFollowed\"\xd9\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x04user\x18\x02 \x01(\v2\x1b.api.community.v1.UserBriefR\x04user\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tpost_type\x18\x06 \x01(\x05R\bpostType\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12\x1b\n" +
	"\tvideo_url\x18\b \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\t \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06locate\x18\n" +
	" \x01(\tR\x06locate\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1f\n" +
	"\vliked_count\x18\f \x01(\x05R\n" +
	"likedCount\x12#\n" +
	"\rcomment_count\x18\r \x01(\x05R\fcommentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bis_liked\x18\x0f \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"is_private\x18\x10 \x01(\bR\tisPrivate\"\x97\x01\n" +
	"\x12GetPostListRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\tpost_type\x18\x02 \x01(\x05R\bpostType\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"T\n" +
	"\x10GetPostListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.api.community.v1.PostR\x04list\"/\n" +
	"\x14GetPostDetailRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"@\n" +
	"\x12GetPostDetailReply\x12*\n" +
	"\x04post\x18\x01 \x01(\v2\x16.api.community.v1.PostR\x04post\"\xa5\x02\n" +
	"\x11CreatePostRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tpost_type\x18\x04 \x01(\x05R\bpostType\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06locate\x18\b \x01(\tR\x06locate\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"is_private\x18\n" +
	" \x01(\bR\tisPrivate\"!\n" +
	"\x0fCreatePostReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"*\n" +
	"\x0fLikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\")\n" +
	"\rLikePostReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11UnlikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"+\n" +
	"\x0fUnlikePostReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbf\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x04user\x18\x02 \x01(\v2\x1b.api.community.v1.UserBriefR\x04user\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vliked_count\x18\x04 \x01(\x05R\n" +
	"likedCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bis_liked\x18\x06 \x01(\bR\aisLiked\"a\n" +
	"\x15GetCommentListRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Z\n" +
	"\x13GetCommentListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12-\n" +
	"\x04list\x18\x02 \x03(\v2\x19.api.community.v1.CommentR\x04list\"I\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"$\n" +
	"\x12CreateCommentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x12LikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\",\n" +
	"\x10LikeCommentReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14UnlikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\".\n" +
	"\x12UnlikeCommentReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\n" +
	"\n" +
	"\x10CommunityService\x12\x7f\n" +
	"\rGetCategories\x12&.api.community.v1.GetCategoriesRequest\x1a$.api.community.v1.GetCategoriesReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/community/categories\x12t\n" +
	"\vGetPostList\x12$.api.community.v1.GetPostListRequest\x1a\".api.community.v1.GetPostListReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/community/posts\x12\x84\x01\n" +
	"\rGetPostDetail\x12&.api.community.v1.GetPostDetailRequest\x1a$.api.community.v1.GetPostDetailReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/community/posts/{post_id}\x12t\n" +
	"\n" +
	"CreatePost\x12#.api.community.v1.CreatePostRequest\x1a!.api.community.v1.CreatePostReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/community/posts\x12z\n" +
	"\bLikePost\x12!.api.community.v1.LikePostRequest\x1a\x1f.api.community.v1.LikePostReply\"*\x82\xd3\xe4\x93\x02$\"\"/v1/community/posts/{post_id}/like\x12\x82\x01\n" +
	"\n" +
	"UnlikePost\x12#.api.community.v1.UnlikePostRequest\x1a!.api.community.v1.UnlikePostReply\",\x82\xd3\xe4\x93\x02&\"$/v1/community/posts/{post_id}/unlike\x12\x90\x01\n" +
	"\x0eGetCommentList\x12'.api.community.v1.GetCommentListRequest\x1a%.api.community.v1.GetCommentListReply\".\x82\xd3\xe4\x93\x02(\x12&/v1/community/posts/{post_id}/comments\x12\x90\x01\n" +
	"\rCreateComment\x12&.api.community.v1.CreateCommentRequest\x1a$.api.community.v1.CreateCommentReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/community/posts/{post_id}/comments\x12\x89\x01\n" +
	"\vLikeComment\x12$.api.community.v1.LikeCommentRequest\x1a\".api.community.v1.LikeCommentReply\"0\x82\xd3\xe4\x93\x02*\"(/v1/community/comments/{comment_id}/like\x12\x91\x01\n" +
	"\rUnlikeComment\x12&.api.community.v1.UnlikeCommentRequest\x1a$.api.community.v1.UnlikeCommentReply\"2\x82\xd3\xe4\x93\x02,\"*/v1/community/comments/{comment_id}/unlikeB\x1fZ\x1dpet-angel/api/community/v1;v1b\x06proto3"

var (
	file_community_v1_community_proto_rawDescOnce sync.Once
	file_community_v1_community_proto_rawDescData []byte
)

func file_community_v1_community_proto_rawDescGZIP() []byte {
	file_community_v1_community_proto_rawDescOnce.Do(func() {
		file_community_v1_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)))
	})
	return file_community_v1_community_proto_rawDescData
}

var file_community_v1_community_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_community_v1_community_proto_goTypes = []any{
	(*Category)(nil),              // 0: api.community.v1.Category
	(*GetCategoriesRequest)(nil),  // 1: api.community.v1.GetCategoriesRequest
	(*GetCategoriesReply)(nil),    // 2: api.community.v1.GetCategoriesReply
	(*UserBrief)(nil),             // 3: api.community.v1.UserBrief
	(*Post)(nil),                  // 4: api.community.v1.Post
	(*GetPostListRequest)(nil),    // 5: api.community.v1.GetPostListRequest
	(*GetPostListReply)(nil),      // 6: api.community.v1.GetPostListReply
	(*GetPostDetailRequest)(nil),  // 7: api.community.v1.GetPostDetailRequest
	(*GetPostDetailReply)(nil),    // 8: api.community.v1.GetPostDetailReply
	(*CreatePostRequest)(nil),     // 9: api.community.v1.CreatePostRequest
	(*CreatePostReply)(nil),       // 10: api.community.v1.CreatePostReply
	(*LikePostRequest)(nil),       // 11: api.community.v1.LikePostRequest
	(*LikePostReply)(nil),         // 12: api.community.v1.LikePostReply
	(*UnlikePostRequest)(nil),     // 13: api.community.v1.UnlikePostRequest
	(*UnlikePostReply)(nil),       // 14: api.community.v1.UnlikePostReply
	(*Comment)(nil),               // 15: api.community.v1.Comment
	(*GetCommentListRequest)(nil), // 16: api.community.v1.GetCommentListRequest
	(*GetCommentListReply)(nil),   // 17: api.community.v1.GetCommentListReply
	(*CreateCommentRequest)(nil),  // 18: api.community.v1.CreateCommentRequest
	(*CreateCommentReply)(nil),    // 19: api.community.v1.CreateCommentReply
	(*LikeCommentRequest)(nil),    // 20: api.community.v1.LikeCommentRequest
	(*LikeCommentReply)(nil),      // 21: api.community.v1.LikeCommentReply
	(*UnlikeCommentRequest)(nil),  // 22: api.community.v1.UnlikeCommentRequest
	(*UnlikeCommentReply)(nil),    // 23: api.community.v1.UnlikeCommentReply
}
var file_community_v1_community_proto_depIdxs = []int32{
	0,  // 0: api.community.v1.GetCategoriesReply.categories:type_name -> api.community.v1.Category
	3,  // 1: api.community.v1.Post.user:type_name -> api.community.v1.UserBrief
	4,  // 2: api.community.v1.GetPostListReply.list:type_name -> api.community.v1.Post
	4,  // 3: api.community.v1.GetPostDetailReply.post:type_name -> api.community.v1.Post
	3,  // 4: api.community.v1.Comment.user:type_name -> api.community.v1.UserBrief
	15, // 5: api.community.v1.GetCommentListReply.list:type_name -> api.community.v1.Comment
	1,  // 6: api.community.v1.CommunityService.GetCategories:input_type -> api.community.v1.GetCategoriesRequest
	5,  // 7: api.community.v1.CommunityService.GetPostList:input_type -> api.community.v1.GetPostListRequest
	7,  // 8: api.community.v1.CommunityService.GetPostDetail:input_type -> api.community.v1.GetPostDetailRequest
	9,  // 9: api.community.v1.CommunityService.CreatePost:input_type -> api.community.v1.CreatePostRequest
	11, // 10: api.community.v1.CommunityService.LikePost:input_type -> api.community.v1.LikePostRequest
	13, // 11: api.community.v1.CommunityService.UnlikePost:input_type -> api.community.v1.UnlikePostRequest
	16, // 12: api.community.v1.CommunityService.GetCommentList:input_type -> api.community.v1.GetCommentListRequest
	18, // 13: api.community.v1.CommunityService.CreateComment:input_type -> api.community.v1.CreateCommentRequest
	20, // 14: api.community.v1.CommunityService.LikeComment:input_type -> api.community.v1.LikeCommentRequest
	22, // 15: api.community.v1.CommunityService.UnlikeComment:input_type -> api.community.v1.UnlikeCommentRequest
	2,  // 16: api.community.v1.CommunityService.GetCategories:output_type -> api.community.v1.GetCategoriesReply
	6,  // 17: api.community.v1.CommunityService.GetPostList:output_type -> api.community.v1.GetPostListReply
	8,  // 18: api.community.v1.CommunityService.GetPostDetail:output_type -> api.community.v1.GetPostDetailReply
	10, // 19: api.community.v1.CommunityService.CreatePost:output_type -> api.community.v1.CreatePostReply
	12, // 20: api.community.v1.CommunityService.LikePost:output_type -> api.community.v1.LikePostReply
	14, // 21: api.community.v1.CommunityService.UnlikePost:output_type -> api.community.v1.UnlikePostReply
	17, // 22: api.community.v1.CommunityService.GetCommentList:output_type -> api.community.v1.GetCommentListReply
	19, // 23: api.community.v1.CommunityService.CreateComment:output_type -> api.community.v1.CreateCommentReply
	21, // 24: api.community.v1.CommunityService.LikeComment:output_type -> api.community.v1.LikeCommentReply
	23, // 25: api.community.v1.CommunityService.UnlikeComment:output_type -> api.community.v1.UnlikeCommentReply
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_community_v1_community_proto_init() }
func file_community_v1_community_proto_init() {
	if File_community_v1_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_v1_community_proto_goTypes,
		DependencyIndexes: file_community_v1_community_proto_depIdxs,
		MessageInfos:      file_community_v1_community_proto_msgTypes,
	}.Build()
	File_community_v1_community_proto = out.File
	file_community_v1_community_proto_goTypes = nil
	file_community_v1_community_proto_depIdxs = nil
}
