server:
  http:
    addr: 0.0.0.0:8000
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 3s
data:
  database:
    driver: mysql
    # root:140001@tcp(47.121.139.174:3306)/pet_angel?parseTime=True&loc=Local
    source: root:140001@tcp(47.121.139.174:3306)/pet_angel?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_secret: "abc123ABC?"
  jwt_ttl: 259200s
# minio 可暂不使用
minio:
  endpoint: "47.121.139.174:9000"
  access_key: "root"
  secret_key: "root1234"
  use_ssl: false
  bucket: "pet-angel"
storage:
  # 服务器部署时的绝对路径
  local_root: "/usr/local/app/pet-angel/data/assets"
  public_prefix: "/static/"
ai:
  model: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
  base_url: "https://api.siliconflow.cn/v1/"
  api_key: "sk-wucfvbppymimfcrmzrtbowbnpquyudkjbjpzahlavmlhddmq"
  max_tokens: 131072
  temperature: 0.5
