// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: avatar/v1/avatar.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 宠物模型
type PetModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 模型ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 模型名称
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                             // 模型资源URL（MinIO）
	ModelType     int32                  `protobuf:"varint,4,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"` // 0=猫 1=狗
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"` // 是否默认
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetModel) Reset() {
	*x = PetModel{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetModel) ProtoMessage() {}

func (x *PetModel) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetModel.ProtoReflect.Descriptor instead.
func (*PetModel) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *PetModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PetModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PetModel) GetModelType() int32 {
	if x != nil {
		return x.ModelType
	}
	return 0
}

func (x *PetModel) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *PetModel) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type GetModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsRequest) Reset() {
	*x = GetModelsRequest{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsRequest) ProtoMessage() {}

func (x *GetModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsRequest.ProtoReflect.Descriptor instead.
func (*GetModelsRequest) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{1}
}

type GetModelsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*PetModel            `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsReply) Reset() {
	*x = GetModelsReply{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsReply) ProtoMessage() {}

func (x *GetModelsReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsReply.ProtoReflect.Descriptor instead.
func (*GetModelsReply) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelsReply) GetModels() []*PetModel {
	if x != nil {
		return x.Models
	}
	return nil
}

// 设置当前模型
type SetPetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int64                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPetModelRequest) Reset() {
	*x = SetPetModelRequest{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPetModelRequest) ProtoMessage() {}

func (x *SetPetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPetModelRequest.ProtoReflect.Descriptor instead.
func (*SetPetModelRequest) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{3}
}

func (x *SetPetModelRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type SetPetModelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPetModelReply) Reset() {
	*x = SetPetModelReply{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPetModelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPetModelReply) ProtoMessage() {}

func (x *SetPetModelReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPetModelReply.ProtoReflect.Descriptor instead.
func (*SetPetModelReply) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{4}
}

func (x *SetPetModelReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 道具
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 道具ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                          // 道具名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`            // 描述文案
	IconPath      string                 `protobuf:"bytes,4,opt,name=icon_path,json=iconPath,proto3" json:"icon_path,omitempty"`  // 图标URL
	CoinCost      int32                  `protobuf:"varint,5,opt,name=coin_cost,json=coinCost,proto3" json:"coin_cost,omitempty"` // 消耗金币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetIconPath() string {
	if x != nil {
		return x.IconPath
	}
	return ""
}

func (x *Item) GetCoinCost() int32 {
	if x != nil {
		return x.CoinCost
	}
	return 0
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{6}
}

type GetItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsReply) Reset() {
	*x = GetItemsReply{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsReply) ProtoMessage() {}

func (x *GetItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsReply.ProtoReflect.Descriptor instead.
func (*GetItemsReply) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemsReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 使用道具
type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{8}
}

func (x *UseItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type UseItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemReply) Reset() {
	*x = UseItemReply{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemReply) ProtoMessage() {}

func (x *UseItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemReply.ProtoReflect.Descriptor instead.
func (*UseItemReply) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{9}
}

func (x *UseItemReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseItemReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 聊天
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{10}
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`         // 本次用户消息的ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                               // 本次用户消息内容回显
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 发送时间 YYYY-MM-DD HH:MM:SS
	AiMessageId   int64                  `protobuf:"varint,4,opt,name=ai_message_id,json=aiMessageId,proto3" json:"ai_message_id,omitempty"` // （可选）AI 回复的消息ID
	AiContent     string                 `protobuf:"bytes,5,opt,name=ai_content,json=aiContent,proto3" json:"ai_content,omitempty"`          // （可选）AI 回复的文本
	AiCreatedAt   string                 `protobuf:"bytes,6,opt,name=ai_created_at,json=aiCreatedAt,proto3" json:"ai_created_at,omitempty"`  // （可选）AI 回复时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_avatar_v1_avatar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_v1_avatar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_avatar_v1_avatar_proto_rawDescGZIP(), []int{11}
}

func (x *ChatReply) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ChatReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatReply) GetAiMessageId() int64 {
	if x != nil {
		return x.AiMessageId
	}
	return 0
}

func (x *ChatReply) GetAiContent() string {
	if x != nil {
		return x.AiContent
	}
	return ""
}

func (x *ChatReply) GetAiCreatedAt() string {
	if x != nil {
		return x.AiCreatedAt
	}
	return ""
}

var File_avatar_v1_avatar_proto protoreflect.FileDescriptor

const file_avatar_v1_avatar_proto_rawDesc = "" +
	"\n" +
	"\x16avatar/v1/avatar.proto\x12\rapi.avatar.v1\x1a\x1cgoogle/api/annotations.proto\"\x9f\x01\n" +
	"\bPetModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"model_type\x18\x04 \x01(\x05R\tmodelType\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"\x12\n" +
	"\x10GetModelsRequest\"A\n" +
	"\x0eGetModelsReply\x12/\n" +
	"\x06models\x18\x01 \x03(\v2\x17.api.avatar.v1.PetModelR\x06models\"/\n" +
	"\x12SetPetModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x03R\amodelId\",\n" +
	"\x10SetPetModelReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x86\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\ticon_path\x18\x04 \x01(\tR\biconPath\x12\x1b\n" +
	"\tcoin_cost\x18\x05 \x01(\x05R\bcoinCost\"\x11\n" +
	"\x0fGetItemsRequest\":\n" +
	"\rGetItemsReply\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.api.avatar.v1.ItemR\x05items\")\n" +
	"\x0eUseItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\"B\n" +
	"\fUseItemReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\vChatRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xca\x01\n" +
	"\tChatReply\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\"\n" +
	"\rai_message_id\x18\x04 \x01(\x03R\vaiMessageId\x12\x1d\n" +
	"\n" +
	"ai_content\x18\x05 \x01(\tR\taiContent\x12\"\n" +
	"\rai_created_at\x18\x06 \x01(\tR\vaiCreatedAt2\x8c\x04\n" +
	"\rAvatarService\x12f\n" +
	"\tGetModels\x12\x1f.api.avatar.v1.GetModelsRequest\x1a\x1d.api.avatar.v1.GetModelsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/avatar/models\x12n\n" +
	"\vSetPetModel\x12!.api.avatar.v1.SetPetModelRequest\x1a\x1f.api.avatar.v1.SetPetModelReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/avatar/model\x12b\n" +
	"\bGetItems\x12\x1e.api.avatar.v1.GetItemsRequest\x1a\x1c.api.avatar.v1.GetItemsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/avatar/items\x12e\n" +
	"\aUseItem\x12\x1d.api.avatar.v1.UseItemRequest\x1a\x1b.api.avatar.v1.UseItemReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/avatar/use-item\x12X\n" +
	"\x04Chat\x12\x1a.api.avatar.v1.ChatRequest\x1a\x18.api.avatar.v1.ChatReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/avatar/chatB\x1cZ\x1apet-angel/api/avatar/v1;v1b\x06proto3"

var (
	file_avatar_v1_avatar_proto_rawDescOnce sync.Once
	file_avatar_v1_avatar_proto_rawDescData []byte
)

func file_avatar_v1_avatar_proto_rawDescGZIP() []byte {
	file_avatar_v1_avatar_proto_rawDescOnce.Do(func() {
		file_avatar_v1_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avatar_v1_avatar_proto_rawDesc), len(file_avatar_v1_avatar_proto_rawDesc)))
	})
	return file_avatar_v1_avatar_proto_rawDescData
}

var file_avatar_v1_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_avatar_v1_avatar_proto_goTypes = []any{
	(*PetModel)(nil),           // 0: api.avatar.v1.PetModel
	(*GetModelsRequest)(nil),   // 1: api.avatar.v1.GetModelsRequest
	(*GetModelsReply)(nil),     // 2: api.avatar.v1.GetModelsReply
	(*SetPetModelRequest)(nil), // 3: api.avatar.v1.SetPetModelRequest
	(*SetPetModelReply)(nil),   // 4: api.avatar.v1.SetPetModelReply
	(*Item)(nil),               // 5: api.avatar.v1.Item
	(*GetItemsRequest)(nil),    // 6: api.avatar.v1.GetItemsRequest
	(*GetItemsReply)(nil),      // 7: api.avatar.v1.GetItemsReply
	(*UseItemRequest)(nil),     // 8: api.avatar.v1.UseItemRequest
	(*UseItemReply)(nil),       // 9: api.avatar.v1.UseItemReply
	(*ChatRequest)(nil),        // 10: api.avatar.v1.ChatRequest
	(*ChatReply)(nil),          // 11: api.avatar.v1.ChatReply
}
var file_avatar_v1_avatar_proto_depIdxs = []int32{
	0,  // 0: api.avatar.v1.GetModelsReply.models:type_name -> api.avatar.v1.PetModel
	5,  // 1: api.avatar.v1.GetItemsReply.items:type_name -> api.avatar.v1.Item
	1,  // 2: api.avatar.v1.AvatarService.GetModels:input_type -> api.avatar.v1.GetModelsRequest
	3,  // 3: api.avatar.v1.AvatarService.SetPetModel:input_type -> api.avatar.v1.SetPetModelRequest
	6,  // 4: api.avatar.v1.AvatarService.GetItems:input_type -> api.avatar.v1.GetItemsRequest
	8,  // 5: api.avatar.v1.AvatarService.UseItem:input_type -> api.avatar.v1.UseItemRequest
	10, // 6: api.avatar.v1.AvatarService.Chat:input_type -> api.avatar.v1.ChatRequest
	2,  // 7: api.avatar.v1.AvatarService.GetModels:output_type -> api.avatar.v1.GetModelsReply
	4,  // 8: api.avatar.v1.AvatarService.SetPetModel:output_type -> api.avatar.v1.SetPetModelReply
	7,  // 9: api.avatar.v1.AvatarService.GetItems:output_type -> api.avatar.v1.GetItemsReply
	9,  // 10: api.avatar.v1.AvatarService.UseItem:output_type -> api.avatar.v1.UseItemReply
	11, // 11: api.avatar.v1.AvatarService.Chat:output_type -> api.avatar.v1.ChatReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_avatar_v1_avatar_proto_init() }
func file_avatar_v1_avatar_proto_init() {
	if File_avatar_v1_avatar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avatar_v1_avatar_proto_rawDesc), len(file_avatar_v1_avatar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avatar_v1_avatar_proto_goTypes,
		DependencyIndexes: file_avatar_v1_avatar_proto_depIdxs,
		MessageInfos:      file_avatar_v1_avatar_proto_msgTypes,
	}.Build()
	File_avatar_v1_avatar_proto = out.File
	file_avatar_v1_avatar_proto_goTypes = nil
	file_avatar_v1_avatar_proto_depIdxs = nil
}
