// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: auth/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名（或手机号/邮箱）
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码（建议 HTTPS 传输）
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// JWT 令牌（放入后续请求 Header 的 Authorization: Bearer <token>）
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// 令牌有效期（单位：秒）
	ExpiresIn     int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 重新登录请求（空）
type ReloginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloginRequest) Reset() {
	*x = ReloginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloginRequest) ProtoMessage() {}

func (x *ReloginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloginRequest.ProtoReflect.Descriptor instead.
func (*ReloginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

// 重新登录响应
type ReloginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true 表示已过期，需要重新登录；false 表示仍然有效
	Expire        bool `protobuf:"varint,1,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloginReply) Reset() {
	*x = ReloginReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloginReply) ProtoMessage() {}

func (x *ReloginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloginReply.ProtoReflect.Descriptor instead.
func (*ReloginReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ReloginReply) GetExpire() bool {
	if x != nil {
		return x.Expire
	}
	return false
}

// 获取用户信息请求（空）
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

// 获取用户信息响应
type GetUserInfoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像URL
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 当前宠物模型ID（未设置则为0）
	ModelId int64 `protobuf:"varint,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// 宠物名称
	PetName string `protobuf:"bytes,5,opt,name=pet_name,json=petName,proto3" json:"pet_name,omitempty"`
	// 宠物头像URL
	PetAvatar string `protobuf:"bytes,6,opt,name=pet_avatar,json=petAvatar,proto3" json:"pet_avatar,omitempty"`
	// 宠物性别 0未知/1男/2女
	PetSex int32 `protobuf:"varint,7,opt,name=pet_sex,json=petSex,proto3" json:"pet_sex,omitempty"`
	// 宠物品类
	Kind string `protobuf:"bytes,8,opt,name=kind,proto3" json:"kind,omitempty"`
	// 体重（kg）
	Weight int32 `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	// 爱好
	Hobby string `protobuf:"bytes,10,opt,name=hobby,proto3" json:"hobby,omitempty"`
	// 个人/宠物简介
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// 金币余额
	Coins int32 `protobuf:"varint,12,opt,name=coins,proto3" json:"coins,omitempty"`
	// 创建时间 YYYY-MM-DD HH:MM:SS
	CreatedAt string `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 当前宠物模型URL（与 pet_models.path 一致，未设置则为空）
	ModelUrl      string `protobuf:"bytes,14,opt,name=model_url,json=modelUrl,proto3" json:"model_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReply) Reset() {
	*x = GetUserInfoReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReply) ProtoMessage() {}

func (x *GetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoReply) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *GetUserInfoReply) GetPetName() string {
	if x != nil {
		return x.PetName
	}
	return ""
}

func (x *GetUserInfoReply) GetPetAvatar() string {
	if x != nil {
		return x.PetAvatar
	}
	return ""
}

func (x *GetUserInfoReply) GetPetSex() int32 {
	if x != nil {
		return x.PetSex
	}
	return 0
}

func (x *GetUserInfoReply) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetUserInfoReply) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GetUserInfoReply) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *GetUserInfoReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetUserInfoReply) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *GetUserInfoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetUserInfoReply) GetModelUrl() string {
	if x != nil {
		return x.ModelUrl
	}
	return ""
}

// 更新用户信息请求（仅包含需要更新的字段）
type UpdateUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 昵称
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像URL
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 当前宠物模型ID
	ModelId int64 `protobuf:"varint,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// 宠物名称
	PetName string `protobuf:"bytes,4,opt,name=pet_name,json=petName,proto3" json:"pet_name,omitempty"`
	// 宠物头像URL
	PetAvatar string `protobuf:"bytes,5,opt,name=pet_avatar,json=petAvatar,proto3" json:"pet_avatar,omitempty"`
	// 宠物性别 0未知/1男/2女
	PetSex int32 `protobuf:"varint,6,opt,name=pet_sex,json=petSex,proto3" json:"pet_sex,omitempty"`
	// 宠物品类
	Kind string `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	// 体重（kg）
	Weight int32 `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	// 爱好（如：散步、逗猫棒）
	Hobby string `protobuf:"bytes,9,opt,name=hobby,proto3" json:"hobby,omitempty"`
	// 个人/宠物简介
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// 金币余额（demo模式允许直接修改）
	Coins         int32 `protobuf:"varint,11,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetPetName() string {
	if x != nil {
		return x.PetName
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPetAvatar() string {
	if x != nil {
		return x.PetAvatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPetSex() int32 {
	if x != nil {
		return x.PetSex
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

// 更新用户信息响应
type UpdateUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReply) Reset() {
	*x = UpdateUserInfoReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReply) ProtoMessage() {}

func (x *UpdateUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\vapi.auth.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Z\n" +
	"\n" +
	"LoginReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"\x10\n" +
	"\x0eReloginRequest\"&\n" +
	"\fReloginReply\x12\x16\n" +
	"\x06expire\x18\x01 \x01(\bR\x06expire\"\x14\n" +
	"\x12GetUserInfoRequest\"\x83\x03\n" +
	"\x10GetUserInfoReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\x03R\amodelId\x12\x19\n" +
	"\bpet_name\x18\x05 \x01(\tR\apetName\x12\x1d\n" +
	"\n" +
	"pet_avatar\x18\x06 \x01(\tR\tpetAvatar\x12\x17\n" +
	"\apet_sex\x18\a \x01(\x05R\x06petSex\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x14\n" +
	"\x05hobby\x18\n" +
	" \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x14\n" +
	"\x05coins\x18\f \x01(\x05R\x05coins\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tmodel_url\x18\x0e \x01(\tR\bmodelUrl\"\xb3\x02\n" +
	"\x15UpdateUserInfoRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\x03R\amodelId\x12\x19\n" +
	"\bpet_name\x18\x04 \x01(\tR\apetName\x12\x1d\n" +
	"\n" +
	"pet_avatar\x18\x05 \x01(\tR\tpetAvatar\x12\x17\n" +
	"\apet_sex\x18\x06 \x01(\x05R\x06petSex\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x14\n" +
	"\x05hobby\x18\t \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x14\n" +
	"\x05coins\x18\v \x01(\x05R\x05coins\"/\n" +
	"\x13UpdateUserInfoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa7\x03\n" +
	"\vAuthService\x12V\n" +
	"\x05Login\x12\x19.api.auth.v1.LoginRequest\x1a\x17.api.auth.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12^\n" +
	"\aRelogin\x12\x1b.api.auth.v1.ReloginRequest\x1a\x19.api.auth.v1.ReloginReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/relogin\x12i\n" +
	"\vGetUserInfo\x12\x1f.api.auth.v1.GetUserInfoRequest\x1a\x1d.api.auth.v1.GetUserInfoReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/auth/user-info\x12u\n" +
	"\x0eUpdateUserInfo\x12\".api.auth.v1.UpdateUserInfoRequest\x1a .api.auth.v1.UpdateUserInfoReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/auth/user-infoB\x1aZ\x18pet-angel/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: api.auth.v1.LoginRequest
	(*LoginReply)(nil),            // 1: api.auth.v1.LoginReply
	(*ReloginRequest)(nil),        // 2: api.auth.v1.ReloginRequest
	(*ReloginReply)(nil),          // 3: api.auth.v1.ReloginReply
	(*GetUserInfoRequest)(nil),    // 4: api.auth.v1.GetUserInfoRequest
	(*GetUserInfoReply)(nil),      // 5: api.auth.v1.GetUserInfoReply
	(*UpdateUserInfoRequest)(nil), // 6: api.auth.v1.UpdateUserInfoRequest
	(*UpdateUserInfoReply)(nil),   // 7: api.auth.v1.UpdateUserInfoReply
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: api.auth.v1.AuthService.Login:input_type -> api.auth.v1.LoginRequest
	2, // 1: api.auth.v1.AuthService.Relogin:input_type -> api.auth.v1.ReloginRequest
	4, // 2: api.auth.v1.AuthService.GetUserInfo:input_type -> api.auth.v1.GetUserInfoRequest
	6, // 3: api.auth.v1.AuthService.UpdateUserInfo:input_type -> api.auth.v1.UpdateUserInfoRequest
	1, // 4: api.auth.v1.AuthService.Login:output_type -> api.auth.v1.LoginReply
	3, // 5: api.auth.v1.AuthService.Relogin:output_type -> api.auth.v1.ReloginReply
	5, // 6: api.auth.v1.AuthService.GetUserInfo:output_type -> api.auth.v1.GetUserInfoReply
	7, // 7: api.auth.v1.AuthService.UpdateUserInfo:output_type -> api.auth.v1.UpdateUserInfoReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
